name: simple hello world

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hello world
        run: echo "Hello-World"
        shell: bash

  bye:
    runs-on: ubuntu-latest
    steps:
      - name: bye
        run: echo "BYE"
        shell: bash
